### PR TITLE
tman

### PR DESCRIPTION
**Pull request by abdinasir-Tman**
changed the borders type to number and behind added the px so i tested and it works correctly you can test

### CODE REVIEW

**Review by isasharafdin — COMMENTED** [review]
thanks, is there anything else needed to fix?

**Review by isasharafdin — APPROVED** [review]
approved this commit. thanks

**Comment by abdinasir-Tman** [comment]
> thanks, is there anything else needed to fix?

may be but am not sure if there something out i will fix it inshaa allah

**Comment by isasharafdin** [comment]
> > thanks, is there anything else needed to fix?
> 
> may be but am not sure if there something out i will fix it inshaa allah

alright. i will approve this pull request.

**Pull request merged**
